version: "3.3"
services:
  master:
    image: voxbox/postgres
    hostname: master
    volumes:
      - master-volume:/var/lib/postgresql
    ports:
      - "5432:5432"      
    environment:
      - DEBUG=false
      - PG_TRUST_LOCALNET=true
      - DB_USER=dbuser
      - DB_PASS=dbuserpass
      - PG_PASSWORD=passw0rd
      - DB_NAME=dbname1,dbname2
      - DB_EXTENSION=citext,hstore,unaccent,pg_trgm
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
    deploy:   
      placement:
        constraints: [node.labels.type == master]     
      restart_policy:
        condition: on-failure   
    networks:
      - postgres

  replica:
    image: voxbox/postgres
    depends_on:
      - "master"    
    ports:
      - "5433:5432"  
    volumes:
      - replica-volume:/var/lib/postgresql
    environment:
      - DEBUG=false
      - PG_TRUST_LOCALNET=true
      - REPLICATION_PORT=5432
      - REPLICATION_HOST=master
      - REPLICATION_MODE=slave
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
      - REPLICATION_SSLMODE=prefer
    deploy:
      placement:
        constraints: [node.labels.type != master]       
      restart_policy:
        condition: on-failure   
    networks:
      - postgres  

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - postgres      

networks:
  postgres: 
volumes:
  master-volume:
    driver: local
  replica-volume:
    driver: local