version: "3.3"
services:
  postgres-master:
    image: voxbox/postgres
    privileged: true
    volumes:
      - postgres-data:/var/lib/postgresql  
    ports:
      - "5432:5432"      
    environment:
      - DEBUG=false
      - PG_TRUST_LOCALNET=true
      - DB_USER=dbuser
      - DB_PASS=dbuserpass
      - PG_PASSWORD=passw0rd
      - DB_NAME=dbname1,dbname2
      - DB_EXTENSION=citext,hstore,unaccent,pg_trgm
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
    deploy:
      restart_policy:
        condition: on-failure   
    networks:
      - postgres

  postgres-slave:
    image: voxbox/postgres
    privileged: true
    ports:
      - "5433:5432"      
    environment:
      - DEBUG=false
      - PG_TRUST_LOCALNET=true
      - REPLICATION_PORT=5432
      - REPLICATION_HOST=master
      - REPLICATION_MODE=slave
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
      - REPLICATION_SSLMODE=prefer
    deploy:
      restart_policy:
        condition: on-failure   
    networks:
      - postgres      
networks:
  postgres: 
volumes:
  postgres-data:         