version: "3.3"
services:
  master:
    image: voxbox-postgres
    privileged: true
    volumes:
      - master-volume:/var/lib/postgresql  
    ports:
      - "5432:5432"      
    environment:
      - DEBUG=false
      - PG_TRUST_LOCALNET=true
      - DB_USER=dbuser
      - DB_PASS=dbuserpass
      - PG_PASSWORD=passw0rd
      - DB_NAME=dbname1,dbname2
      - DB_EXTENSION=citext,hstore,unaccent,pg_trgm
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
    deploy:
      placement:
        constraints: [node.labels.type == manager]    
      restart_policy:
        condition: on-failure   
    networks:
      - postgres

     
networks:
  postgres: 
volumes:
  master-volume: